export const practiceAreas = [
  {
    slug: "income-tax",
    title: "Income Tax",
    metaDescription:
      "Advisory, compliance and representation on income tax matters for individuals, businesses and institutions.",
    lead: "Advisory, compliance and representation on income tax matters for individuals, businesses and institutions.",
    cardDescription: "Advisory, returns, assessments, notices, audits and representation.",
    category: "federal",
    categoryLabel: "FEDERAL TAXATION",
    categoryTag: "FEDERAL",
    ctaTopic: "income tax",
    expertise: [
      "Return filing and annual compliance",
      "Tax assessments, audits and departmental inquiries",
      "Responses to notices and show-cause proceedings",
      "Advance and withholding tax reconciliation",
      "Tax planning for individuals and businesses",
    ],
  },
  {
    slug: "sales-tax",
    title: "Sales Tax",
    metaDescription:
      "Registration, compliance and dispute resolution across Pakistan's sales tax framework.",
    lead: "Registration, compliance and dispute resolution across Pakistan's sales tax framework.",
    cardDescription: "Registration, compliance, disputes and proceedings relating to sales tax.",
    category: "federal",
    categoryLabel: "FEDERAL TAXATION",
    categoryTag: "FEDERAL",
    ctaTopic: "sales tax",
    expertise: [
      "Sales tax registration and de-registration",
      "Input/output tax reconciliation and compliance",
      "Sales tax audits and departmental assessments",
      "Refund claims and processing",
      "Representation in sales tax disputes",
    ],
  },
  {
    slug: "withholding-tax",
    title: "Withholding Tax",
    metaDescription: "Guidance on withholding obligations, deductions, statements and related disputes.",
    lead: "Guidance on withholding obligations, deductions, statements and related disputes.",
    cardDescription: "Guidance on withholding obligations, deductions, statements and disputes.",
    category: "federal",
    categoryLabel: "FEDERAL TAXATION",
    categoryTag: "FEDERAL",
    ctaTopic: "withholding tax",
    expertise: [
      "Withholding tax obligations and applicable rates",
      "Withholding statement filing and reconciliation",
      "Exemption and reduced-rate certificates",
      "Deduction disputes and reconciliation issues",
      "Compliance reviews for withholding agents",
    ],
  },
  {
    slug: "fbr-matters",
    title: "FBR Matters",
    metaDescription:
      "Professional assistance with notices, inquiries, audits and departmental proceedings before the FBR.",
    lead: "Professional assistance with notices, inquiries, audits and departmental proceedings before the FBR.",
    cardDescription: "Professional assistance with notices, inquiries, audits and departmental proceedings.",
    category: "federal",
    categoryLabel: "FEDERAL TAXATION",
    categoryTag: "FEDERAL",
    ctaTopic: "fbr matters",
    expertise: [
      "Response to FBR notices and inquiries",
      "Representation in audit and inquiry proceedings",
      "Show-cause notice proceedings",
      "Departmental correspondence and liaison",
      "General compliance advisory",
    ],
  },
  {
    slug: "customs-duties",
    title: "Customs & Duties",
    metaDescription: "Tax and duty matters connected with imports, exports and customs proceedings.",
    lead: "Tax and duty matters connected with imports, exports and customs proceedings.",
    cardDescription: "Tax and duty matters connected with imports, exports and customs issues.",
    category: "federal",
    categoryLabel: "FEDERAL TAXATION",
    categoryTag: "FEDERAL",
    ctaTopic: "customs & duties",
    expertise: [
      "Import and export duty matters",
      "Customs valuation disputes",
      "Clearance and tariff classification issues",
      "Representation before customs authorities",
      "Regulatory and anti-dumping duty matters",
    ],
  },
  {
    slug: "provincial-taxes",
    title: "Provincial Taxes",
    metaDescription: "Support on applicable provincial revenue and taxation matters.",
    lead: "Support on applicable provincial revenue and taxation matters.",
    cardDescription: "Support on applicable provincial revenue and taxation matters.",
    category: "provincial",
    categoryLabel: "PROVINCIAL & SECTOR-SPECIFIC",
    categoryTag: "PROVINCIAL",
    ctaTopic: "provincial taxes",
    expertise: [
      "Provincial sales tax on services",
      "Property and professional tax matters",
      "Proceedings before provincial revenue authorities",
      "Registration and ongoing compliance",
      "Representation in provincial tax disputes",
    ],
  },
  {
    slug: "banking-taxes",
    title: "Banking Taxes",
    metaDescription: "Tax advisory and compliance matters specific to banks and financial institutions.",
    lead: "Tax advisory and compliance matters specific to banks and financial institutions.",
    cardDescription: "Tax advisory and compliance matters specific to banks and financial institutions.",
    category: "provincial",
    categoryLabel: "PROVINCIAL & SECTOR-SPECIFIC",
    categoryTag: "SECTOR-SPECIFIC",
    ctaTopic: "banking taxes",
    expertise: [
      "Taxation of banking company income",
      "Withholding tax on banking transactions",
      "Compliance with sector-specific tax regulations",
      "Advisory on financial instruments and transactions",
      "Representation in banking-sector tax disputes",
    ],
  },
  {
    slug: "tax-advisory",
    title: "Tax Advisory",
    metaDescription: "Practical advice for businesses, transactions, structures and ongoing tax obligations.",
    lead: "Practical advice for businesses, transactions, structures and ongoing tax obligations.",
    cardDescription: "Practical advice for businesses, transactions, structures and ongoing obligations.",
    category: "advisory",
    categoryLabel: "ADVISORY, LITIGATION & IP",
    categoryTag: "ADVISORY",
    ctaTopic: "tax advisory",
    expertise: [
      "Transaction structuring and tax impact review",
      "Corporate and business tax planning",
      "Due diligence support",
      "Ongoing compliance advisory",
      "Cross-border and international tax considerations",
    ],
  },
  {
    slug: "tax-litigation",
    title: "Tax Litigation",
    metaDescription: "Representation in tax disputes, appeals and litigation before the relevant forums.",
    lead: "Representation in tax disputes, appeals and litigation before the relevant forums.",
    cardDescription: "Representation in tax disputes, appeals and litigation before relevant forums.",
    category: "advisory",
    categoryLabel: "ADVISORY, LITIGATION & IP",
    categoryTag: "LITIGATION",
    ctaTopic: "tax litigation",
    expertise: [
      "Representation before the Commissioner (Appeals)",
      "Proceedings before the Appellate Tribunal Inland Revenue",
      "Tax references before the High Court",
      "Stay applications and interim relief",
      "Settlement and alternate dispute resolution",
    ],
  },
  {
    slug: "trademark-registration",
    title: "Trademark Registration",
    metaDescription:
      "Assistance with trademark filing, registration and related intellectual property matters.",
    lead: "Assistance with trademark filing, registration and related intellectual property matters.",
    cardDescription: "Assistance with trademark filing, registration and related intellectual property matters.",
    category: "advisory",
    categoryLabel: "ADVISORY, LITIGATION & IP",
    categoryTag: "IP",
    ctaTopic: "trademark registration",
    expertise: [
      "Trademark search and clearance",
      "Filing and registration with the Trade Marks Registry",
      "Renewal and portfolio management",
      "Objection and opposition proceedings",
      "Enforcement and infringement advisory",
    ],
  },
];

export const categories = [
  { key: "federal", label: "FEDERAL TAXATION" },
  { key: "provincial", label: "PROVINCIAL & SECTOR-SPECIFIC" },
  { key: "advisory", label: "ADVISORY, LITIGATION & IP" },
];

export function getPracticeArea(slug) {
  return practiceAreas.find((area) => area.slug === slug);
}
